package org.zyb.crimeintent.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.zyb.crimeintent.model.Crime;

import org.zyb.crimeintent.dao.CrimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig crimeDaoConfig;

    private final CrimeDao crimeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        crimeDaoConfig = daoConfigMap.get(CrimeDao.class).clone();
        crimeDaoConfig.initIdentityScope(type);

        crimeDao = new CrimeDao(crimeDaoConfig, this);

        registerDao(Crime.class, crimeDao);
    }
    
    public void clear() {
        crimeDaoConfig.clearIdentityScope();
    }

    public CrimeDao getCrimeDao() {
        return crimeDao;
    }

}
